/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author brandonluismenesessolorzano
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(new Color(0, 30, 180));
        panelBusqueda.setVisible(false);
        panelRegistro.setVisible(false);
        panelReservar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        panelBusqueda = new javax.swing.JPanel();
        lblBusqueda = new javax.swing.JLabel();
        lblDNIB = new javax.swing.JLabel();
        txtBusquedaDNI = new javax.swing.JTextField();
        panelRegistro = new javax.swing.JPanel();
        lblRegistro = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtRegistroDNI = new javax.swing.JTextField();
        txtRegistroNombre = new javax.swing.JTextField();
        txtRegistroApellido = new javax.swing.JTextField();
        txtRegistroTelefono = new javax.swing.JTextField();
        txtRegistroCorreo = new javax.swing.JTextField();
        panelReservar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroPersonas = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        mnuBar = new javax.swing.JMenuBar();
        mnuBusqueda = new javax.swing.JMenu();
        mnuReservar = new javax.swing.JMenu();
        mnuRegistro = new javax.swing.JMenu();
        mnuModificarReserva = new javax.swing.JMenu();
        mnuAñadirHabitacion = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setBackground(new java.awt.Color(102, 102, 255));

        lblBusqueda.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lblBusqueda.setText("Búsqueda");

        lblDNIB.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblDNIB.setText("DNI:");

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(lblDNIB)
                .addGap(36, 36, 36)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBusqueda)
                    .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblBusqueda)
                .addGap(18, 18, 18)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDNIB)
                    .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        lblRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lblRegistro.setText("Registro");

        lblDNI.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblDNI.setText("DNI:");

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblApellido.setText("Apellido:");

        lblTelefono.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTelefono.setText("Telefono:");

        lblCorreo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCorreo.setText("Correo::");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblDNI)
                    .addComponent(lblApellido)
                    .addComponent(lblTelefono)
                    .addComponent(lblCorreo))
                .addGap(108, 108, 108)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRegistroDNI)
                    .addComponent(txtRegistroNombre)
                    .addComponent(txtRegistroApellido)
                    .addComponent(txtRegistroTelefono)
                    .addComponent(txtRegistroCorreo))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblRegistro)
                .addGap(39, 39, 39)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtRegistroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtRegistroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtRegistroApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtRegistroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo)
                    .addComponent(txtRegistroCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel9.setText("Reservar");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Numero de personas");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione tipo de habitación");

        txtNumeroPersonas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Simple", "Junior", "Junior Suite", "Suite", "Matrimonial", "Presidencial" }));

        javax.swing.GroupLayout panelReservarLayout = new javax.swing.GroupLayout(panelReservar);
        panelReservar.setLayout(panelReservarLayout);
        panelReservarLayout.setHorizontalGroup(
            panelReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarLayout.createSequentialGroup()
                .addGroup(panelReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservarLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(panelReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(80, 80, 80)
                        .addGroup(panelReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeroPersonas)
                            .addComponent(jComboBox1, 0, 196, Short.MAX_VALUE)))
                    .addGroup(panelReservarLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel9)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelReservarLayout.setVerticalGroup(
            panelReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservarLayout.createSequentialGroup()
                        .addComponent(txtNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReservarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        mnuBusqueda.setText("Busqueda");
        mnuBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuBusquedaMouseClicked(evt);
            }
        });
        mnuBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusquedaActionPerformed(evt);
            }
        });
        mnuBar.add(mnuBusqueda);

        mnuReservar.setText("Reservar");
        mnuReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuReservarMouseClicked(evt);
            }
        });
        mnuReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReservarActionPerformed(evt);
            }
        });
        mnuBar.add(mnuReservar);

        mnuRegistro.setText("Registro");
        mnuRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuRegistroMouseClicked(evt);
            }
        });
        mnuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroActionPerformed(evt);
            }
        });
        mnuBar.add(mnuRegistro);

        mnuModificarReserva.setText("Modificar Reserva");
        mnuBar.add(mnuModificarReserva);

        mnuAñadirHabitacion.setText("Añadir Habitación");
        mnuBar.add(mnuAñadirHabitacion);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusquedaActionPerformed
        // TODO add your handling code here:
        panelBusqueda.setVisible(true);
        panelRegistro.setVisible(false);
        panelReservar.setVisible(false);
    }//GEN-LAST:event_mnuBusquedaActionPerformed

    private void mnuReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReservarActionPerformed
        // TODO add your handling code here:
        panelRegistro.setVisible(true);
        panelBusqueda.setVisible(false);
        panelReservar.setVisible(false);
    }//GEN-LAST:event_mnuReservarActionPerformed

    private void mnuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroActionPerformed
        // TODO add your handling code here:
        panelReservar.setVisible(true);
        panelRegistro.setVisible(false);
        panelBusqueda.setVisible(false);
    }//GEN-LAST:event_mnuRegistroActionPerformed

    private void mnuBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBusquedaMouseClicked
        // TODO add your handling code here:
        panelBusqueda.setVisible(true);
        panelRegistro.setVisible(false);
        panelReservar.setVisible(false);
       
    }//GEN-LAST:event_mnuBusquedaMouseClicked

    private void mnuReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuReservarMouseClicked
        // TODO add your handling code here:
        panelReservar.setVisible(true);
        panelRegistro.setVisible(false);
        panelBusqueda.setVisible(false);
    }//GEN-LAST:event_mnuReservarMouseClicked

    private void mnuRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuRegistroMouseClicked
        // TODO add your handling code here:
        panelRegistro.setVisible(true);
        panelBusqueda.setVisible(false);
        panelReservar.setVisible(false);
    }//GEN-LAST:event_mnuRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDNIB;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JMenu mnuAñadirHabitacion;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuBusqueda;
    private javax.swing.JMenu mnuModificarReserva;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenu mnuReservar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelReservar;
    private javax.swing.JTextField txtBusquedaDNI;
    private javax.swing.JTextField txtNumeroPersonas;
    private javax.swing.JTextField txtRegistroApellido;
    private javax.swing.JTextField txtRegistroCorreo;
    private javax.swing.JTextField txtRegistroDNI;
    private javax.swing.JTextField txtRegistroNombre;
    private javax.swing.JTextField txtRegistroTelefono;
    // End of variables declaration//GEN-END:variables
}
